# Generated by Django 2.2.28 on 2023-08-17 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
                ('time_consume', models.TimeField()),
                ('steps', models.TextField()),
                ('image', models.ImageField(upload_to='userrecipe/image/images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrecipe_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
